"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {DOCUMENT_TYPES,DOCUMENT_STATUSES,documentTitle,type BusinessDocument} from "../../../lib/documents/model";
import styles from "../admin.module.css";
export function DocumentList({documents}:{documents:BusinessDocument[]}){
 const [search,setSearch]=useState("");const [language,setLanguage]=useState("");const [status,setStatus]=useState("");const [type,setType]=useState("");const [sort,setSort]=useState("date");
 const rows=useMemo(()=>documents.filter(d=>{
 const q=d.snapshot.quote;return (!language||d.language===language)&&(!status||d.status===status)&&(!type||d.type===type)&&[d.number,q.documentNumber,q.ref,q.customer.name,q.destinationCountry,q.destinationPort,d.type,d.language,d.status,...q.items.flatMap(v=>[v.make,v.model,v.vin])].join(" ").toLowerCase().includes(search.toLowerCase());
 }).sort((a,b)=>{const value=(d:BusinessDocument)=>{const q=d.snapshot.quote;return sort==="customer"?q.customer.name:sort==="vehicle"?q.items.map(v=>`${v.make} ${v.model}`).join(" "):sort==="vin"?q.items.map(v=>v.vin).join(" "):sort==="number"?d.number:sort==="quote"?q.documentNumber||q.ref:sort==="country"?q.destinationCountry:sort==="port"?q.destinationPort:sort==="type"?d.type:sort==="language"?d.language:sort==="status"?d.status:d.created_at;};return sort==="date"?value(b).localeCompare(value(a)):value(a).localeCompare(value(b));}),[documents,search,language,status,type,sort]);
 return <><div className={styles.form}><div className={styles.grid}><label className={styles.wide}>Search documents<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Customer, vehicle, VIN, number, destination…"/></label><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{Object.entries(DOCUMENT_TYPES).map(([k,v])=><option key={k} value={k}>{v[0]}</option>)}</select></label><label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="">All languages</option><option value="en">English</option><option value="es">Español</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{DOCUMENT_STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}>{["date","customer","vehicle","vin","number","quote","type","language","country","port","status"].map(s=><option key={s}>{s}</option>)}</select></label></div></div><p role="status">{rows.length} documents</p><div className={styles.recordList}>{rows.map(d=><Link className={styles.documentCard} key={d.id} href={`/admin/documents/${d.id}`}><strong>{d.number}</strong><span>{documentTitle(d.type,d.language)}</span><span>{d.snapshot.quote.customer.name} · {d.snapshot.quote.items.map(v=>`${v.make} ${v.model}`).join(", ")}</span><small>{d.language==="es"?"Español":"English"} · {d.status} · {new Date(d.created_at).toLocaleDateString()}</small></Link>)}</div>{!rows.length&&<div className={styles.emptyState}><p>No documents match. Create a document or clear the filters.</p><Link href="/admin/documents/new">Generate document</Link></div>}</>;
}
