"use client";
import {useRef,useState} from "react";
import {useRouter} from "next/navigation";
import type {AdminQuoteSummary} from "../../../lib/crm";
import type {Operation} from "../../../lib/documents/model";
import {useDraft} from "../use-draft";
import styles from "../admin.module.css";
export const operationFields={payment:["amount","currency","reference","date","method"],shipment:["tracking","vessel","departure","arrival","destinationPort"],customs:["broker","reference","amount","currency","date","notes"],vehicle:["make","model","year","vin","price","currency","notes"]} as const;
const states={payment:["pending","confirmed","rejected"],shipment:["booked","in_transit","arrived","completed"],customs:["pending","cleared","completed"],vehicle:["available","reserved","sold"]};
export function OperationEditor({kind,quotes,initial,initialRef=""}:{kind:Operation["kind"];quotes:AdminQuoteSummary[];initial?:Operation;initialRef?:string}){
 const router=useRouter();const lock=useRef(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const [form,setForm]=useState({id:initial?.id||"",quote_ref:initial?.quote_ref||initialRef,title:initial?.title||"",status:initial?.status||states[kind][0],data:initial?.data||{currency:"USD"},version:initial?.version});
 const draft=useDraft(`${kind}:${initial?.id||"new"}`,form,d=>{if(d&&typeof d.title==="string")setForm(d);});
 async function save(e:React.FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError("");const id=form.id||crypto.randomUUID();setForm(v=>({...v,id}));try{const r=await fetch("/api/admin/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,id,kind})});const d=await r.json();if(!r.ok)throw new Error(d.error);await draft.clear();router.push(`/admin/operations?kind=${kind}`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Save failed. Retry.");}finally{lock.current=false;setBusy(false);}}
 return <form className={styles.form} onSubmit={save}><p role="status" className={styles.draftStatus}>{draft.state}</p><div className={styles.grid}><label>Title<input required maxLength={300} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Order<select required={kind!=="vehicle"} disabled={!!initial} value={form.quote_ref} onChange={e=>{const q=quotes.find(q=>q.ref===e.target.value);setForm({...form,quote_ref:e.target.value,data:{...form.data,currency:q?.currency||"USD"}});}}><option value="">Choose order</option>{quotes.map(q=><option value={q.ref} key={q.ref}>{q.customerName} · {q.documentNumber||q.ref}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{states[kind].map(s=><option key={s}>{s}</option>)}</select></label>{operationFields[kind].map(field=><label key={field}>{field.replace(/([A-Z])/g," $1")}{field==="currency"?<select value={form.data[field]||"USD"} onChange={e=>setForm({...form,data:{...form.data,[field]:e.target.value}})}>{["USD","EUR","CNY"].map(c=><option key={c}>{c}</option>)}</select>:<input required={kind==="payment"&&["amount","reference","date"].includes(field)} type={["date","departure","arrival"].includes(field)?"date":["amount","price","year"].includes(field)?"number":"text"} min={field==="amount"?0.01:0} step={field==="year"?1:0.01} value={form.data[field]||""} onChange={e=>setForm({...form,data:{...form.data,[field]:e.target.value}})}/>}</label>)}</div>{error&&<p className={styles.formError} role="alert">{error}</p>}<div className={styles.formActions}><button className={styles.btn} disabled={busy}>{busy?"Saving…":"Save record"}</button></div></form>;
}
