import Link from "next/link";
import {notFound} from "next/navigation";
import {AdminShell} from "../../admin-shell";
import {getPool} from "../../../../lib/crm";
import {listDocuments} from "../../../../lib/admin-store";
import {DocumentList} from "../../documents/document-list";
import {CustomerForm} from "../customer-form";
import styles from "../../admin.module.css";
export const dynamic="force-dynamic";
export default async function Customer({params}:{params:Promise<{id:string}>}){const id=Number((await params).id);if(!Number.isSafeInteger(id)||id<1)notFound();const [customer,orders,documents,operations,activity]=await Promise.all([getPool().query("SELECT * FROM customers WHERE id=$1",[id]),getPool().query("SELECT ref,document_number,status,currency,cif_total FROM quotes WHERE customer_id=$1 ORDER BY created_at DESC",[id]),listDocuments(undefined,id),getPool().query("SELECT o.* FROM admin_operations o JOIN quotes q ON q.ref=o.quote_ref WHERE q.customer_id=$1 ORDER BY o.created_at DESC",[id]),getPool().query("SELECT a.* FROM admin_activity a JOIN quotes q ON q.ref=a.quote_ref WHERE q.customer_id=$1 ORDER BY a.created_at DESC LIMIT 50",[id])]);const c=customer.rows[0];if(!c)notFound();const initial={id,updatedAt:new Date(c.updated_at).toISOString(),name:c.name,phone:c.phone||"",email:c.email||"",address:c.address||"",city:c.city||"",country:c.country||"",notes:c.notes||""};return <AdminShell><h1>{c.name}</h1><nav className={styles.filterRow}>{["Overview","Orders","Documents","Payments","Shipping","Customs","Activity"].map(n=><a href={`#${n.toLowerCase()}`} key={n}>{n}</a>)}</nav><section id="overview" className={styles.section}><h2>Overview</h2><p>{[c.email,c.phone,c.country].filter(Boolean).join(" · ")}</p><details><summary>Edit customer</summary><CustomerForm initial={initial}/></details></section><section id="orders" className={styles.section}><h2>Vehicles / orders & quotes</h2>{orders.rows.map(q=><p key={q.ref}><Link href={`/admin/quotes/${q.ref}`}>{q.document_number||q.ref}</Link> · {q.status} · {q.currency} {Number(q.cif_total).toLocaleString()}</p>)}{!orders.rows.length&&<p>No orders yet.</p>}<Link href="/admin/quotes/new">Create quote</Link></section><section id="documents" className={styles.section}><h2>Documents</h2><DocumentList documents={documents}/></section>{([['payment','Payments'],['shipment','Shipping'],['customs','Customs']] as const).map(([kind,label])=><section id={label.toLowerCase()} className={styles.section} key={kind}><h2>{label}</h2>{operations.rows.filter(r=>r.kind===kind).map(r=><p key={r.id}><Link href={`/admin/operations?kind=${kind}&id=${r.id}`}>{r.title}</Link> · {r.status}</p>)}<Link href={`/admin/operations?kind=${kind}&new=1`}>Add record</Link></section>)}<section id="activity" className={styles.section}><h2>Activity</h2>{activity.rows.map(a=><p key={a.id}>{a.action} · {a.reference} · {new Date(a.created_at).toLocaleString()}</p>)}{!activity.rows.length&&<p>No recorded activity yet.</p>}</section></AdminShell>;}
