import type {Metadata, Viewport} from "next";import "./globals.css";
import {Suspense} from "react";
import {AutoTranslate} from "./auto-translate";
// Use the locally hosted company mark for link previews and structured data.
const SITE_ORIGIN="https://www.nindgeauto.com";
const SITE_LOGO_URL=`${SITE_ORIGIN}/images/KkwGH.png`;
const SEO_DESCRIPTION="Compra vehículos nuevos y usados de China para Venezuela y Sudamérica con Nindge Automobile: inspección profesional, documentación de exportación, precios transparentes y logística internacional.";
export const metadata:Metadata={metadataBase:new URL(SITE_ORIGIN),title:{default:"Autos de China para Venezuela y Sudamérica | Nindge Automobile",template:"%s | Nindge Automobile"},description:SEO_DESCRIPTION,keywords:["autos de China en Venezuela","autos de China en Colombia","importar autos de China a Perú","vehículos chinos en Chile","importar vehículos de China","vehículos nuevos China","carros usados China","exportación de autos a Sudamérica","SUV chinos","camionetas chinas"],authors:[{name:"Nindge Automobile"}],creator:"Nindge Automobile",publisher:"Nindge Automobile",category:"Automotive",alternates:{canonical:"/"},robots:{index:true,follow:true,googleBot:{index:true,follow:true,"max-image-preview":"large","max-snippet":-1,"max-video-preview":-1}},icons:{icon:"/images/KkwGH.png",shortcut:"/images/KkwGH.png",apple:"/images/KkwGH.png"},openGraph:{siteName:"Nindge Automobile",type:"website",locale:"es_VE",alternateLocale:["es_CO","es_PE","es_CL","es_EC","es_AR","pt_BR"],url:SITE_ORIGIN,title:"Autos de China para Venezuela y Sudamérica | Nindge Automobile",description:SEO_DESCRIPTION,images:[{url:SITE_LOGO_URL,width:128,height:128,alt:"Nindge Automobile"}]},twitter:{card:"summary",title:"Autos de China para Venezuela y Sudamérica | Nindge Automobile",description:SEO_DESCRIPTION,images:[SITE_LOGO_URL]}};
export const viewport:Viewport={width:"device-width",initialScale:1,viewportFit:"cover"};
const structuredData={"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":`${SITE_ORIGIN}/#organization`,"name":"Nindge Automobile","url":SITE_ORIGIN,"logo":SITE_LOGO_URL,"description":SEO_DESCRIPTION,"email":"info@nindgeauto.com","telephone":"+86 150 3217 8759","address":{"@type":"PostalAddress","addressRegion":"Fujian","addressCountry":"CN"},"areaServed":["Venezuela","Colombia","Peru","Chile","Ecuador","Bolivia","Argentina","Brazil","Uruguay","Paraguay"].map((name)=>({"@type":"Country","name":name})),"contactPoint":{"@type":"ContactPoint","telephone":"+86 150 3217 8759","contactType":"sales","areaServed":"South America","availableLanguage":["Spanish","Portuguese","English","Chinese"]}},{"@type":"WebSite","@id":`${SITE_ORIGIN}/#website`,"url":SITE_ORIGIN,"name":"Nindge Automobile Sudamérica","inLanguage":["es","pt-BR","en"],"publisher":{"@id":`${SITE_ORIGIN}/#organization`},"potentialAction":{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":`${SITE_ORIGIN}/vehicles?q={search_term_string}`},"query-input":"required name=search_term_string"}}]};
// lang="en" is the authored source language. app/auto-translate.tsx updates
// document.documentElement.lang only when a visitor explicitly selects a
// translation language. Spanish-market SEO is carried by the metadata export above.
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="en" data-scroll-behavior="smooth"><body><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/><Suspense fallback={null}><AutoTranslate/></Suspense>{children}</body></html>}
