import type {Metadata, Viewport} from "next";import "./globals.css";
import {Suspense} from "react";
import {AutoTranslate} from "./auto-translate";
// Same local logo asset used site-wide (header/footer in app/ui.tsx, admin
// quote PDF letterhead) — used here too so link previews (WhatsApp, iMessage,
// social) show the same mark as the site itself. Hosted in public/ rather
// than hotlinked from img.hainaauto.com, which changed its content mid-session
// once already. Absolute URL (not resolved via metadataBase, which still
// points at hainaauto.com — a different, older site, not this deployment)
// since social platforms fetch og:image directly rather than through Next.
const SITE_LOGO_URL="https://www.hainaautochina.com/hainaauto-logo.webp";
const SEO_DESCRIPTION="Compra vehículos nuevos y usados de China para Venezuela con HainaAuto: inspección profesional, documentación de exportación, precios transparentes y logística internacional.";
const SHARE_DESCRIPTION="HainaAuto 专注于中国新车与二手车采购、专业验车及出口服务，为全球客户提供可靠车源、出口文件和国际物流支持。";
export const metadata:Metadata={metadataBase:new URL("https://www.hainaautochina.com"),title:{default:"Autos de China para Venezuela | HainaAuto",template:"%s | HainaAuto Venezuela"},description:SEO_DESCRIPTION,keywords:["autos de China en Venezuela","comprar carros chinos","importar vehículos de China","vehículos nuevos China","carros usados China","exportación de autos a Venezuela","SUV chinos","camionetas chinas"],authors:[{name:"HainaAuto"}],creator:"HainaAuto",publisher:"HainaAuto",category:"Automotive",robots:{index:true,follow:true,googleBot:{index:true,follow:true,"max-image-preview":"large","max-snippet":-1,"max-video-preview":-1}},openGraph:{siteName:"HainaAuto",type:"website",locale:"es_VE",title:"Autos de China para Venezuela | HainaAuto",description:SHARE_DESCRIPTION,images:[{url:SITE_LOGO_URL,width:128,height:128,alt:"HainaAuto"}]},twitter:{card:"summary",title:"Autos de China para Venezuela | HainaAuto",description:SHARE_DESCRIPTION,images:[SITE_LOGO_URL]}};
export const viewport:Viewport={width:"device-width",initialScale:1,viewportFit:"cover"};
const structuredData={"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":"https://www.hainaautochina.com/#organization","name":"HainaAuto","url":"https://www.hainaautochina.com","logo":SITE_LOGO_URL,"description":SEO_DESCRIPTION,"email":"sales@hainaautochina.com","telephone":"+86 1553 102 6121","address":{"@type":"PostalAddress","addressRegion":"Fujian","addressCountry":"CN"},"areaServed":{"@type":"Country","name":"Venezuela"},"contactPoint":{"@type":"ContactPoint","telephone":"+86 1553 102 6121","contactType":"sales","availableLanguage":["Spanish","English","Chinese"]}},{"@type":"WebSite","@id":"https://www.hainaautochina.com/#website","url":"https://www.hainaautochina.com","name":"HainaAuto Venezuela","inLanguage":"es-VE","publisher":{"@id":"https://www.hainaautochina.com/#organization"},"potentialAction":{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://www.hainaautochina.com/vehicles?q={search_term_string}"},"query-input":"required name=search_term_string"}}]};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="es-VE" data-scroll-behavior="smooth"><body><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/><Suspense fallback={null}><AutoTranslate/></Suspense>{children}</body></html>}
