// Customer-facing destination choices. Codes follow UN/LOCODE where a
// commonly used code is available; labels use the port names customers see
// on carrier documents. "Other / not sure" remains available because final
// carrier routing can use a nearby terminal or inland destination.
export type ShippingPort = { name: string; code?: string };
export type ShippingCountry = { country: string; iso2: string; ports: ShippingPort[] };

export const SHIPPING_COUNTRIES: ShippingCountry[] = [
  {country:"Venezuela",iso2:"VE",ports:[{name:"Puerto Cabello",code:"VEPBL"},{name:"La Guaira",code:"VELAG"},{name:"Maracaibo",code:"VEMAR"},{name:"Guanta",code:"VEGUT"}]},
  {country:"Colombia",iso2:"CO",ports:[{name:"Cartagena",code:"COCTG"},{name:"Buenaventura",code:"COBUN"},{name:"Barranquilla",code:"COBAQ"},{name:"Santa Marta",code:"COSMR"}]},
  {country:"United States",iso2:"US",ports:[{name:"Los Angeles, CA",code:"USLAX"},{name:"Long Beach, CA",code:"USLGB"},{name:"New York / New Jersey",code:"USNYC"},{name:"Savannah, GA",code:"USSAV"},{name:"Houston, TX",code:"USHOU"},{name:"Miami, FL",code:"USMIA"},{name:"Baltimore, MD",code:"USBAL"}]},
  {country:"Mexico",iso2:"MX",ports:[{name:"Manzanillo",code:"MXZLO"},{name:"Veracruz",code:"MXVER"},{name:"Lázaro Cárdenas",code:"MXLZC"},{name:"Altamira",code:"MXATM"}]},
  {country:"Panama",iso2:"PA",ports:[{name:"Balboa",code:"PABLB"},{name:"Manzanillo International Terminal",code:"PAMIT"},{name:"Colón",code:"PACOL"},{name:"Cristóbal",code:"PACTB"}]},
  {country:"Ecuador",iso2:"EC",ports:[{name:"Guayaquil",code:"ECGYE"},{name:"Posorja",code:"ECPSJ"},{name:"Manta",code:"ECMEC"}]},
  {country:"Peru",iso2:"PE",ports:[{name:"Callao",code:"PECLL"},{name:"Paita",code:"PEPAI"},{name:"Matarani",code:"PEMRI"}]},
  {country:"Chile",iso2:"CL",ports:[{name:"San Antonio",code:"CLSAI"},{name:"Valparaíso",code:"CLVAP"},{name:"Iquique",code:"CLIQQ"},{name:"Antofagasta",code:"CLANF"}]},
  {country:"Brazil",iso2:"BR",ports:[{name:"Santos",code:"BRSSZ"},{name:"Rio de Janeiro",code:"BRRIO"},{name:"Paranaguá",code:"BRPNG"},{name:"Itajaí",code:"BRITJ"}]},
  {country:"Argentina",iso2:"AR",ports:[{name:"Buenos Aires",code:"ARBUE"},{name:"Zárate",code:"ARZAE"},{name:"Rosario",code:"ARROS"}]},
  {country:"Uruguay",iso2:"UY",ports:[{name:"Montevideo",code:"UYMVD"},{name:"Nueva Palmira",code:"UYNVP"}]},
  {country:"Dominican Republic",iso2:"DO",ports:[{name:"Caucedo",code:"DOCAU"},{name:"Haina",code:"DOHAI"},{name:"Santo Domingo",code:"DOSDQ"}]},
  {country:"Jamaica",iso2:"JM",ports:[{name:"Kingston",code:"JMKIN"},{name:"Montego Bay",code:"JMMBJ"}]},
  {country:"Trinidad and Tobago",iso2:"TT",ports:[{name:"Port of Spain",code:"TTPOS"},{name:"Point Lisas",code:"TTPTS"}]},
  {country:"United Arab Emirates",iso2:"AE",ports:[{name:"Jebel Ali",code:"AEJEA"},{name:"Khalifa Port",code:"AEKHL"},{name:"Sharjah",code:"AESHJ"}]},
  {country:"Saudi Arabia",iso2:"SA",ports:[{name:"Jeddah Islamic Port",code:"SAJED"},{name:"King Abdulaziz Port, Dammam",code:"SADMM"}]},
  {country:"Oman",iso2:"OM",ports:[{name:"Sohar",code:"OMSOH"},{name:"Salalah",code:"OMSLL"},{name:"Duqm",code:"OMDQM"}]},
  {country:"South Africa",iso2:"ZA",ports:[{name:"Durban",code:"ZADUR"},{name:"Cape Town",code:"ZACPT"},{name:"Gqeberha (Port Elizabeth)",code:"ZAPLZ"}]},
  {country:"Nigeria",iso2:"NG",ports:[{name:"Lagos (Apapa)",code:"NGLOS"},{name:"Tin Can Island",code:"NGTIN"},{name:"Onne",code:"NGONN"}]},
  {country:"Ghana",iso2:"GH",ports:[{name:"Tema",code:"GHTEM"},{name:"Takoradi",code:"GHTKD"}]},
  {country:"Kenya",iso2:"KE",ports:[{name:"Mombasa",code:"KEMBA"},{name:"Lamu",code:"KELAU"}]},
  {country:"Tanzania",iso2:"TZ",ports:[{name:"Dar es Salaam",code:"TZDAR"},{name:"Tanga",code:"TZTGT"}]},
  {country:"Russia",iso2:"RU",ports:[{name:"Vladivostok",code:"RUVVO"},{name:"Novorossiysk",code:"RUNVS"},{name:"Saint Petersburg",code:"RULED"}]},
  {country:"Georgia",iso2:"GE",ports:[{name:"Poti",code:"GEPTI"},{name:"Batumi",code:"GEBUS"}]},
  {country:"Philippines",iso2:"PH",ports:[{name:"Manila",code:"PHMNL"},{name:"Batangas",code:"PHBTG"},{name:"Cebu",code:"PHCEB"}]},
  {country:"Australia",iso2:"AU",ports:[{name:"Melbourne",code:"AUMEL"},{name:"Sydney",code:"AUSYD"},{name:"Brisbane",code:"AUBNE"},{name:"Fremantle",code:"AUFRE"},{name:"Adelaide",code:"AUADL"}]},
  {country:"New Zealand",iso2:"NZ",ports:[{name:"Auckland",code:"NZAKL"},{name:"Tauranga",code:"NZTRG"},{name:"Lyttelton",code:"NZLYT"},{name:"Wellington",code:"NZWLG"}]},
  {country:"Canada",iso2:"CA",ports:[{name:"Vancouver",code:"CAVAN"},{name:"Montreal",code:"CAMTR"},{name:"Halifax",code:"CAHAL"},{name:"Prince Rupert",code:"CAPRR"}]},
  {country:"United Kingdom",iso2:"GB",ports:[{name:"Southampton",code:"GBSOU"},{name:"London Gateway",code:"GBLGP"},{name:"Felixstowe",code:"GBFXT"},{name:"Liverpool",code:"GBLIV"},{name:"Bristol",code:"GBBRS"}]},
  {country:"Germany",iso2:"DE",ports:[{name:"Bremerhaven",code:"DEBRV"},{name:"Hamburg",code:"DEHAM"},{name:"Wilhelmshaven",code:"DEWVN"}]},
  {country:"Netherlands",iso2:"NL",ports:[{name:"Rotterdam",code:"NLRTM"},{name:"Amsterdam",code:"NLAMS"}]},
  {country:"Belgium",iso2:"BE",ports:[{name:"Antwerp-Bruges",code:"BEANR"},{name:"Zeebrugge",code:"BEZEE"}]},
  {country:"France",iso2:"FR",ports:[{name:"Le Havre",code:"FRLEH"},{name:"Marseille-Fos",code:"FRMRS"},{name:"Dunkerque",code:"FRDKK"}]},
  {country:"Spain",iso2:"ES",ports:[{name:"Valencia",code:"ESVLC"},{name:"Barcelona",code:"ESBCN"},{name:"Algeciras",code:"ESALG"},{name:"Vigo",code:"ESVGO"}]},
  {country:"Portugal",iso2:"PT",ports:[{name:"Sines",code:"PTSIE"},{name:"Lisbon",code:"PTLIS"},{name:"Leixoes",code:"PTLEI"}]},
  {country:"Italy",iso2:"IT",ports:[{name:"Genoa",code:"ITGOA"},{name:"Livorno",code:"ITLIV"},{name:"Gioia Tauro",code:"ITGIT"},{name:"Civitavecchia",code:"ITCVV"}]},
  {country:"Greece",iso2:"GR",ports:[{name:"Piraeus",code:"GRPIR"},{name:"Thessaloniki",code:"GRSKG"}]},
  {country:"Turkey",iso2:"TR",ports:[{name:"Ambarli",code:"TRAMB"},{name:"Mersin",code:"TRMER"},{name:"Izmir",code:"TRIZM"},{name:"Gemlik",code:"TRGEM"}]},
  {country:"Poland",iso2:"PL",ports:[{name:"Gdansk",code:"PLGDN"},{name:"Gdynia",code:"PLGDY"},{name:"Szczecin",code:"PLSZZ"}]},
  {country:"Sweden",iso2:"SE",ports:[{name:"Gothenburg",code:"SEGOT"},{name:"Stockholm",code:"SESTO"}]},
  {country:"Norway",iso2:"NO",ports:[{name:"Oslo",code:"NOOSL"},{name:"Drammen",code:"NODRM"},{name:"Bergen",code:"NOBGO"}]},
  {country:"Finland",iso2:"FI",ports:[{name:"Helsinki",code:"FIHEL"},{name:"Hanko",code:"FIHKO"},{name:"Kotka",code:"FIKTK"}]},
  {country:"Romania",iso2:"RO",ports:[{name:"Constanta",code:"ROCND"}]},
  {country:"Ukraine",iso2:"UA",ports:[{name:"Odesa",code:"UAODS"},{name:"Chornomorsk",code:"UAILK"},{name:"Pivdennyi",code:"UAYUZ"}]},
  {country:"Egypt",iso2:"EG",ports:[{name:"Alexandria",code:"EGALY"},{name:"Port Said",code:"EGPSD"},{name:"Damietta",code:"EGDAM"},{name:"Ain Sokhna",code:"EGAIS"}]},
  {country:"Morocco",iso2:"MA",ports:[{name:"Tanger Med",code:"MAPTM"},{name:"Casablanca",code:"MACAS"},{name:"Agadir",code:"MAAGA"}]},
  {country:"Algeria",iso2:"DZ",ports:[{name:"Algiers",code:"DZALG"},{name:"Oran",code:"DZORN"},{name:"Djen Djen",code:"DZDJE"}]},
  {country:"Tunisia",iso2:"TN",ports:[{name:"Rades",code:"TNRDS"},{name:"La Goulette",code:"TNLGO"}]},
  {country:"Libya",iso2:"LY",ports:[{name:"Tripoli",code:"LYTIP"},{name:"Misurata",code:"LYMRA"},{name:"Benghazi",code:"LYBEN"}]},
  {country:"Senegal",iso2:"SN",ports:[{name:"Dakar",code:"SNDKR"}]},
  {country:"Cote d'Ivoire",iso2:"CI",ports:[{name:"Abidjan",code:"CIABJ"},{name:"San Pedro",code:"CISPY"}]},
  {country:"Cameroon",iso2:"CM",ports:[{name:"Douala",code:"CMDLA"},{name:"Kribi",code:"CMKBI"}]},
  {country:"Angola",iso2:"AO",ports:[{name:"Luanda",code:"AOLAD"},{name:"Lobito",code:"AOLOB"},{name:"Namibe",code:"AOMSZ"}]},
  {country:"Mozambique",iso2:"MZ",ports:[{name:"Maputo",code:"MZMPM"},{name:"Beira",code:"MZBEW"},{name:"Nacala",code:"MZMNC"}]},
  {country:"Namibia",iso2:"NA",ports:[{name:"Walvis Bay",code:"NAWVB"},{name:"Luderitz",code:"NALUD"}]},
  {country:"Djibouti",iso2:"DJ",ports:[{name:"Djibouti",code:"DJJIB"},{name:"Doraleh",code:"DJDCT"}]},
  {country:"Qatar",iso2:"QA",ports:[{name:"Hamad Port",code:"QAHMD"},{name:"Doha",code:"QADOH"}]},
  {country:"Kuwait",iso2:"KW",ports:[{name:"Shuwaikh",code:"KWSWK"},{name:"Shuaiba",code:"KWSAA"}]},
  {country:"Bahrain",iso2:"BH",ports:[{name:"Khalifa Bin Salman Port",code:"BHKBS"}]},
  {country:"Jordan",iso2:"JO",ports:[{name:"Aqaba",code:"JOAQJ"}]},
  {country:"Israel",iso2:"IL",ports:[{name:"Haifa",code:"ILHFA"},{name:"Ashdod",code:"ILASH"}]},
  {country:"Iraq",iso2:"IQ",ports:[{name:"Umm Qasr",code:"IQUQR"}]},
  {country:"Pakistan",iso2:"PK",ports:[{name:"Karachi",code:"PKKHI"},{name:"Port Qasim",code:"PKBQM"},{name:"Gwadar",code:"PKGWD"}]},
  {country:"India",iso2:"IN",ports:[{name:"Nhava Sheva (JNPT)",code:"INNSA"},{name:"Mundra",code:"INMUN"},{name:"Chennai",code:"INMAA"},{name:"Kolkata",code:"INCCU"},{name:"Cochin",code:"INCOK"}]},
  {country:"Bangladesh",iso2:"BD",ports:[{name:"Chattogram",code:"BDCGP"},{name:"Mongla",code:"BDMGL"}]},
  {country:"Sri Lanka",iso2:"LK",ports:[{name:"Colombo",code:"LKCMB"},{name:"Hambantota",code:"LKHBA"}]},
  {country:"Myanmar",iso2:"MM",ports:[{name:"Yangon",code:"MMRGN"},{name:"Thilawa",code:"MMTLA"}]},
  {country:"Thailand",iso2:"TH",ports:[{name:"Laem Chabang",code:"THLCH"},{name:"Bangkok",code:"THBKK"}]},
  {country:"Vietnam",iso2:"VN",ports:[{name:"Ho Chi Minh City",code:"VNSGN"},{name:"Hai Phong",code:"VNHPH"},{name:"Da Nang",code:"VNDAD"},{name:"Cai Mep",code:"VNCMT"}]},
  {country:"Malaysia",iso2:"MY",ports:[{name:"Port Klang",code:"MYPKG"},{name:"Tanjung Pelepas",code:"MYTPP"},{name:"Penang",code:"MYPEN"}]},
  {country:"Singapore",iso2:"SG",ports:[{name:"Singapore",code:"SGSIN"}]},
  {country:"Indonesia",iso2:"ID",ports:[{name:"Tanjung Priok",code:"IDTPP"},{name:"Tanjung Perak",code:"IDSUB"},{name:"Belawan",code:"IDBLW"},{name:"Makassar",code:"IDMAK"}]},
  {country:"South Korea",iso2:"KR",ports:[{name:"Busan",code:"KRPUS"},{name:"Incheon",code:"KRINC"},{name:"Pyeongtaek",code:"KRPTK"}]},
  {country:"Japan",iso2:"JP",ports:[{name:"Yokohama",code:"JPYOK"},{name:"Kobe",code:"JPUKB"},{name:"Nagoya",code:"JPNGO"},{name:"Osaka",code:"JPOSA"}]},
  {country:"Mongolia",iso2:"MN",ports:[{name:"Tianjin transit to Zamyn-Uud",code:"CNTXG"}]},
  {country:"Costa Rica",iso2:"CR",ports:[{name:"Puerto Limon",code:"CRLIO"},{name:"Caldera",code:"CRCAL"},{name:"Moin",code:"CRMOB"}]},
  {country:"Guatemala",iso2:"GT",ports:[{name:"Puerto Quetzal",code:"GTPRQ"},{name:"Santo Tomas de Castilla",code:"GTSTC"}]},
  {country:"Honduras",iso2:"HN",ports:[{name:"Puerto Cortes",code:"HNPCR"},{name:"San Lorenzo",code:"HNSLO"}]},
  {country:"El Salvador",iso2:"SV",ports:[{name:"Acajutla",code:"SVAQJ"}]},
  {country:"Nicaragua",iso2:"NI",ports:[{name:"Corinto",code:"NICIO"}]},
  {country:"Cuba",iso2:"CU",ports:[{name:"Mariel",code:"CUMAR"},{name:"Havana",code:"CUHAV"},{name:"Santiago de Cuba",code:"CUSCU"}]},
  {country:"Bahamas",iso2:"BS",ports:[{name:"Nassau",code:"BSNAS"},{name:"Freeport",code:"BSFPO"}]},
  {country:"Guyana",iso2:"GY",ports:[{name:"Georgetown",code:"GYGEO"}]},
  {country:"Suriname",iso2:"SR",ports:[{name:"Paramaribo",code:"SRPBM"}]},
  {country:"Paraguay",iso2:"PY",ports:[{name:"Asuncion",code:"PYASU"},{name:"Villeta",code:"PYVIL"}]},
  {country:"Bolivia",iso2:"BO",ports:[{name:"Arica transit to Bolivia",code:"CLARI"},{name:"Iquique transit to Bolivia",code:"CLIQQ"}]},
].sort((a,b)=>a.country.localeCompare(b.country));
